"""initial schema sqlite

Revision ID: 15f8f8f0640c
Revises: 
Create Date: 2026-05-24 13:07:34.303745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f8f8f0640c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=200), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authors',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_backfill_state',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('backfilled_through', sa.DateTime(), nullable=True),
    sa.Column('last_message_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_channels_server_id', 'channels', ['server_id'], unique=False)
    op.create_table('digests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_digests_channel_id_period_start', 'digests', ['channel_id', 'period', 'period_start'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('reply_to_id', sa.BigInteger(), nullable=True),
    sa.Column('embeds', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_author_id', 'messages', ['author_id'], unique=False)
    op.create_index('ix_messages_channel_id_created_at', 'messages', ['channel_id', 'created_at'], unique=False)
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_table('reactions',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('emoji', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('message_id', 'emoji', 'user_id'),
    sa.UniqueConstraint('message_id', 'emoji', 'user_id', name='uq_reactions_message_emoji_user')
    )
    op.create_table('servers',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threads',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('thread_created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wiki_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('page_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('source_refs', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_wiki_pages_page_type', 'wiki_pages', ['page_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wiki_pages_page_type', table_name='wiki_pages')
    op.drop_table('wiki_pages')
    op.drop_table('threads')
    op.drop_table('servers')
    op.drop_table('reactions')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_index('ix_messages_channel_id_created_at', table_name='messages')
    op.drop_index('ix_messages_author_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_digests_channel_id_period_start', table_name='digests')
    op.drop_table('digests')
    op.drop_index('ix_channels_server_id', table_name='channels')
    op.drop_table('channels')
    op.drop_table('channel_backfill_state')
    op.drop_table('authors')
    op.drop_table('attachments')
    # ### end Alembic commands ###
